### ISSUE TITLE
[Bug]: 报错

### ISSUE THREAD

**Issue by Ezgx** [Eurkon/hexo-theme-butterfly-eurkon#6]
### 使用的 Butterfly 版本？ | What version of Butterfly are you use?

4.5.1

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的瀏覽器？ || What browse are you using?

Chrome

### 使用的系統？ || What operating system are you using?

Windows

### 問題描述 | Describe the bug

```bash
> hexo s

INFO  Validating config
INFO  
  ===================================================================

      #####  #    # ##### ##### ###### #####  ###### #      #   #    
      #    # #    #   #     #   #      #    # #      #       # #     
      #####  #    #   #     #   #####  #    # #####  #        #      
      #    # #    #   #     #   #      #####  #      #        #      
      #    # #    #   #     #   #      #   #  #      #        #      
      #####   ####    #     #   ###### #    # #      ######   #      

                            4.5.1
  ===================================================================
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/ . Press Ctrl+C to stop.
ERROR Render HTML failed: index.html
TypeError: Cannot read properties of undefined (reading 'map')
    at Hexo.<anonymous> (D:\aurora-test\themes\butterfly\scripts\helpers\random.js:12:31)
    at Hexo.tryCatcher (D:\aurora-test\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\aurora-test\node_modules\bluebird\js\release\method.js:15:34)
    at D:\aurora-test\node_modules\hexo\lib\extend\filter.js:67:52
    at tryCatcher (D:\aurora-test\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (D:\aurora-test\node_modules\bluebird\js\release\reduce.js:166:18)
    at Object.gotAccum (D:\aurora-test\node_modules\bluebird\js\release\reduce.js:155:25)
    at Object.tryCatcher (D:\aurora-test\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\aurora-test\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\aurora-test\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\aurora-test\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\aurora-test\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\aurora-test\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\aurora-test\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\aurora-test\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\aurora-test\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (node:internal/timers:466:21)
Unhandled rejection TypeError: Cannot read properties of undefined (reading 'map')
    at Hexo.<anonymous> (D:\aurora-test\themes\butterfly\scripts\helpers\random.js:12:31)
    at Hexo.tryCatcher (D:\aurora-test\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\aurora-test\node_modules\bluebird\js\release\method.js:15:34)
    at D:\aurora-test\node_modules\hexo\lib\extend\filter.js:67:52
    at tryCatcher (D:\aurora-test\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (D:\aurora-test\node_modules\bluebird\js\release\reduce.js:166:18)
    at Object.gotAccum (D:\aurora-test\node_modules\bluebird\js\release\reduce.js:155:25)
    at Object.tryCatcher (D:\aurora-test\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\aurora-test\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\aurora-test\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\aurora-test\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\aurora-test\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\aurora-test\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\aurora-test\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\aurora-test\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\aurora-test\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (node:internal/timers:466:21)
```

### 出現問題網站 | Website

no

**Comment by baispace** [comment]
同样哈，麻烦解答下。

**Comment by Eurkon** [comment]
https://github.com/Eurkon/hexo-theme-butterfly-eurkon/commit/d3cf916faed5ba83249ffdaf42eaa90c54f96d9f
